### ISSUE TITLE
cannot change language to Portuguese and Chinese in settings menu

### ISSUE THREAD

**Issue by iptux** [skullone/android_firewall#24]

**Comment by iptux** [comment]
is it possiable to add a option to follow system language settings?

**Comment by skullone** [comment]
I can add the ability to set it back to the system language.  

As for the Portuguese and Chinese languages.  I'm still working on those.  The issue is with their locale code.  zh-rCN for the Simplified Chinese for example.  Using zh-rCN in the code doesn't make the app change to the Simplified Chinese translation.  If I put the translation in values-zh I can make it work but then I have Simplified Chinese translation where a Traditional Chinese translation should exist.  I want to make sure I do it right.  Hopefully I can get it figured out for 2.1.9.

**Comment by skullone** [comment]
Does the app now default to English which is making the lack of Portuguese
and Simplified Chinese more of a problem?

**Comment by iptux** [comment]
yes, English is the default

**Comment by skullone** [comment]
My bad.  I'll push a fix tomorrow.

**Comment by skullone** [comment]
I have pushed the fix to Github.  I will post the app to the Play Store later today after I get some testing done on it first as I fixed a NullPointerException as well in 2.1.9.  My sincere apologies for the mix up.  After you confirm things are working correctly for you again I will close the issue.

**Comment by iptux** [comment]
will be fixed in issue #26
