### ISSUE TITLE
[not very BUG]android firewall not work when in proxy

### ISSUE THREAD

**Issue by alvinrxg** [skullone/android_firewall#35]
Hi all,
just installed AdBlock Plus to disable some ads
after set the [proxy of adblock plus](https://adblockplus.org/en/android-config) `localhost:2020` every block app are now allowed to access the internet...it seems the android firewall is not working now.
1. **without** proxy of AdBlock Plus, android firewall works fine.
2. **with** the proxy of AdBlock Plus, every app access the internet through the proxy(i think).

eh well, i need to learn the script from [droidwall](https://code.google.com/p/droidwall/wiki/CustomScripts)

i hope you could add the situation when people use proxy :)

**Comment by skullone** [comment]
I don't have WiFi right now to confirm but judging by what they say on
their FAQ, when you're using the proxy all data is routed through the ABP
app which is the issue.  I'm willing to bet if you blocked ABP in the
firewall _nothing_ would get out.  ;)

May I ask why you're using the proxy on a rooted device?  The proxy isn't
needed if you're rooted and ABP admits having root is desired due to the
ability to fully filter all connections.  I just confirmed this with AF and
ABP on my Galaxy S 3.  Ads are blocked and no apps can access the Internet.

**Comment by alvinrxg** [comment]
@skullone aha, thx for your hint! I just didn't know why dose adp need the root permission...and now I closed the proxy and let abp directly block ads with root permission. And now both adp and AF are now work fine.
Thank you :-)
