### ISSUE TITLE
Phone hang out when enabling firewall

### ISSUE THREAD

**Issue by qsPhil** [skullone/android_firewall#45]
when I enable the firewall rules the phone freezes then reboots. If I don't disable wireless conectection immediately after it boots-up it will freeze an reboot again. 

Phone information:
Samsung Galaxy S4 - SPH-L720
rooted and unlocked
android 4.2.2
kernel 3.4 0-953334
Baseband MF9

**Comment by skullone** [comment]
That's the Sprint model isn't it?

**Comment by qsPhil** [comment]
Wow! That was a quick response. :)

Yes is the Spring model.

**Comment by skullone** [comment]
As far as I can tell the issue is the MF9 OTA.  Only the Sprint S4 has this
issue and ONLY if it is on MF9.  There were users with no issues and as
soon as they installed MF9 it broke.  I did extensive testing with others
about this issue and I firmly believe AF isn't the problem.

Logs and debugging showed that AF was working properly but when the kernel
actually tries to apply the iptables it reboots.  The version of the
iptables binary doesn't matter either as I did test builds where users
could use the binary included with the app or use the binary included in
their kernel.  Both have the same issue.  I don't know what Sprint/Samsung
did in MF9 but they broke it good.

My recommendation is try a custom kernel and see if things get corrected.
 Otherwise you'll have to wait for an update from Sprint to see if it
corrects it.
