### ISSUE TITLE
Shortcuts to activate profiles

### ISSUE THREAD

**Issue by lschweiss** [skullone/android_firewall#56]
There needs to be application shortcuts to activate each profile and enable or disable the firewall.  

This way profiles can be switched automatically with tools like llama or MacroDroid.

**Comment by skullone** [comment]
I will look into this.  Please note that functionality like this currently exists in AF via the Tasker/Locale plugin.

**Comment by laphlaw** [comment]
On that note, I have a related question.. I'm trying to write a shell script to enable/disable the firewall rules (trying to schedule times when the firewall is active via a cron job).

I'm not too familiar with iptables, but where do you save the rules? Couldn't I just manually run iptables with whatever rules are saved?

If that is not possible, what would be the easiest way to enable/disable the rules in an automated fashion? I'm not really looking to a plugin, but a shell script.  Thanks

**Comment by skullone** [comment]
Rules are not saved anywhere.  They are hardcoded.  The only variables for
the rules themselves are the chain name and the UID for the app to be
allowed/disallowed.

Easiest method of automation is by using Tasker and the plugin included in
AF.  If you want to build a shell script instead of using the plugin you
probably need to build the script by using the commands from the source
code.  All the iptables rules can be found in Api.java.

Thanks!

**Comment by skullone** [comment]
This has been added to version 2.3.3 and is complete.  Please e-mail me as I would appreciate another set of eyes to test this with Macrodroid and Llama.

**Comment by lschweiss** [comment]
Jason,

I'd be happy to test it on both Llama and MacroDroid.

Do you have an installer package I can use?

-Chip

**Comment by skullone** [comment]
Chip email me at emaileditedout and i'll send you the link.

**Comment by skullone** [comment]
This has added in version 2.3.3.
