### ISSUE TITLE
SSHtunnel and Android Firewall

### ISSUE THREAD

**Issue by gsdgsdf** [skullone/android_firewall#59]
Weird behavior displayed when both are running (SSHtunnel in global proxy mode) either of these happen :
1) apps do not have access to the internet whatsoever
2) apps can access the internet but are not tunneled through ssh

Similarly, for individual app tunneling mode, I get this behavior for the selected apps.

If either of the apps is running alone, they work correctly. I assume this requires a similar fix to what openvpn did before, but I don't think I can figure it out myself :(

Setting VPN enabled in the firewall does not seem to change anything.

**Comment by skullone** [comment]
Please send me the link to the SSH app you are using.

Thanks!

**Comment by gsdgsdf** [comment]
https://play.google.com/store/apps/details?id=org.sshtunnel

Thanks :)

**Comment by skullone** [comment]
My apologies for the late reply.  I was out of town for the Thanksgiving
holiday and then had to catch up with work.  I will take a look at this
issue so thanks for the Play Store link.

Unfortunately if I find a fix it will not be added to version 2.3.3 which
will hit the Play Store today or tomorrow.  If a fix can be found for this
issue it will be included in 2.3.4.

Thanks!

-Jason

**Comment by gsdgsdf** [comment]
Quite frankly I am just amazed. Thanks for the reply and the update :)

**Comment by skullone** [comment]
Upon further review using Global Proxy mode in that app makes modifications to the iptables for its own use. This is not an AF issue.

I have no control over the chains that the ssh app uses and how they are applied.  This is why you see two different issues happening.  Those issues are based on which apps chains are first in iptables.

**Comment by eldorado1384** [comment]
hi, Like "gsdgsdf" said, I have some issues in this field,

but first i must tank you for your support ;)

I'm using "psiphon" SSH+ tunnel: https://play.google.com/store/apps/details?id=gov.bbg.voa&hl=en

I disallowed some app (for example NFS) to access internet at all, but when I start psiphon in mode that tunnel whole device, NFS can access internet (and so all apps can), I thought maybe there is no way to disable internet access when some tunneling application is sending whole device traffic, is it like that? is there any way when psiphon is running, firewall rules still work? it's kind of VPN, so what is "VPN support" in settings?

tnx

**Comment by skullone** [comment]
With Psiphon it acts as a proxy.  That's why the rules aren't applied.  You allow Psiphon and Psiphon filters all data through itself so everything has access.  

For Psiphon to work with VPN Support it would have to create a new interface and send the data through that interface. For example if you were to use something like OpenVPN you would get a new interface (commonly something like tun0) when connected to the VPN.  All VPN data travels through that interface.  So VPN Support can filter that because it can allow or deny data to tun0.  That is something Psiphon does not do since all data passes through Psiphon itself.
