### ISSUE TITLE
Prevent Individual Connections Per Application?

### ISSUE THREAD

**Issue by PartisanEntity** [skullone/android_firewall#72]
Sorry if I misunderstood the way Android Firewall is meant to work.

Expected Behavior: In addition to allowing full access per applications, also be able to allow/deny individual connections per app. For example allow access for app XYZ but deny it from being able to connect to ad server ABC.

I cannot find this functionality in Android Firewall.

**Comment by skullone** [comment]
That is not how AF works.  It's an all or nothing deal for blocking data.

If you want to block just a specific ad server you would need to create a
custom rule.

Sorry if I misunderstood the way Android Firewall is meant to work.

Expected Behavior: In addition to allowing full access per applications,
also be able to allow/deny individual connections per app. For example
allow access for app XYZ but deny it from being able to connect to ad
server ABC.

I cannot find this functionality in Android Firewall.

## 

Reply to this email directly or view it on
GitHubhttps://github.com/skullone/android_firewall/issues/72
.

**Comment by PartisanEntity** [comment]
Got it, thanks for the explanation.
