### ISSUE TITLE
The Bluetooth PAN support

### ISSUE THREAD

**Issue by houfukude** [skullone/android_firewall#79]
Android firewall does not work on the client when i connected a device by Bluetooth Internet Access.

**Comment by skullone** [comment]
Please send me an error report from within AF while using Bluetooth for
Internet access.

**Comment by houfukude** [comment]
i donot know how to catch the error report. 
I just use device A open bluetooth with bluetooth tethering on. this is devicA setting
![devicea](https://cloud.githubusercontent.com/assets/3358382/3857597/f9baf1fa-1f04-11e4-8e9d-a2de00f30b43.png)

 and share the internet to device B. this is the deviceB setting
![deviceb](https://cloud.githubusercontent.com/assets/3358382/3857610/384bee88-1f05-11e4-8b35-95a5bc87d77d.png)

And the device B installed the Android Firewall . 
I tried every options even IPV6,VPN,LAN settings ,but all the apps has the internet access.that looks like the Android Firewall does not work.

**Comment by skullone** [comment]
Menu - Send Error Report from within the firewall app.

Did you enable Tethering Support as well?  That is needed.

**Comment by houfukude** [comment]
I consider that the Tethering Support  is only for the device that share internet . not for the device  accept the internet share. and i already send the error report to the dev mail box

**Comment by skullone** [comment]
You are correct.  You have a unique use case in you are pairing one android
device to another via BT and want AF to function on the second device.  You
are the first to ever bring something like this to me.

In the past everybody wanted to share their device's BT with something like
a laptop.  Due to that BT interfaces are only opened up when tethering is
enabled but in your case that wouldn't even correct it.

You need custom rules as what you want to do is not supported.  I will see
what I can do about supporting this in a future build though.

You need one of two rules:

$IPTABLES -I "droidwall" 1 -o bt-pan+ -j "droidwall-3g"

$IPTABLES -I "droidwall" 1 -o bt-pan+ -j "droidwall-wifi"

If you use the -3g option the rules from Data will be applied to the
BT connection.  If you use the -wifi option teh rules from WiFi will
be applied to the BT connection.

Add one of those to the Custom Scripts option and reapply the
firewall.  The firewall rules from whichever option you choose should
now function correctly while using BT.

**Comment by houfukude** [comment]
thanks a lot.that's help me solve a big problem .I will try and give a feedback.
